### ISSUE TITLE
Add Unit Test coverage

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/pyklatchat#18]

**Comment by NeonKirill** [comment]
@NeonDaniel here it is a very broad topic, as currently me and sometimes @NeonBohdan are the only who maintain this repo, it may be considered less prioritized to cover those with unittests. However, if there are any particular scenarios you feel like must be validated please mention those

**Comment by NeonDaniel** [comment]
As mentioned in https://github.com/NeonGeckoCom/pyklatchat/issues/64, I think util modules may make sense to be moved to and imported from `neon-utils` (with unit tests). I am unaware of a convenient way to test the webserver components and agree we are limited on resources to investigate it further.

**Comment by NeonKirill** [comment]
Closing this as for now there is insufficient development resources to imply end-to-end testing
