### ISSUE TITLE
[BUG] Docker image tags do not match branches

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/pyklatchat#77]
### Description

The current automation pushes images to ghcr on `PR` instead of `Merge`, so tags are applied before PR approval/merge.

### Other Notes

The `dev` and `master` tags should always match those branches. We could add another tag (`pre`, `alpha`) for builds on PR if that is helpful, but currently it is unclear what commit is associated with the `dev` tag and the `master` tag is being updated before changes are tested/marked stable.

**Comment by NeonKirill** [comment]
@NeonDaniel added alpha as a separate branch, for beta we are going to use dev, and when we get to stable - it will be main
